llm:
  api_type: "openai"  # or azure / ollama / groq etc.
  model: "deepseek/deepseek-r1-0528:free"  # or gpt-3.5-turbo
  base_url: "https://openrouter.ai/api/v1"  # or forward url / other llm url
  api_key: "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"